package sjd3.registerapi.product;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

public final class ProductOuterClass {
  private ProductOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProductOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Product)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();
  }
  /**
   * Protobuf type {@code Product}
   */
  public  static final class Product extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Product)
      ProductOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Product.newBuilder() to construct.
    private Product(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Product() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Product();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Product(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProductOuterClass.internal_static_Product_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProductOuterClass.internal_static_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Product.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Product)) {
        return super.equals(obj);
      }
      Product other = (Product) obj;

      if (getId()
          != other.getId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Product parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Product parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Product parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Product parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Product parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Product parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Product parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Product parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Product parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Product parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Product parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Product parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Product prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Product}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Product)
        ProductOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProductOuterClass.internal_static_Product_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProductOuterClass.internal_static_Product_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Product.class, Builder.class);
      }

      // Construct using sdj3.registerservice2.product.ProductOuterClass.Product.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProductOuterClass.internal_static_Product_descriptor;
      }

      @Override
      public Product getDefaultInstanceForType() {
        return Product.getDefaultInstance();
      }

      @Override
      public Product build() {
        Product result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Product buildPartial() {
        Product result = new Product(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Product) {
          return mergeFrom((Product)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Product other) {
        if (other == Product.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Product parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Product) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Product)
    }

    // @@protoc_insertion_point(class_scope:Product)
    private static final Product DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Product();
    }

    public static Product getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Product>
        PARSER = new com.google.protobuf.AbstractParser<Product>() {
      @Override
      public Product parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Product(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Product> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Product> getParserForType() {
      return PARSER;
    }

    @Override
    public Product getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AnimalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Animal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();
  }
  /**
   * Protobuf type {@code Animal}
   */
  public  static final class Animal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Animal)
      AnimalOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Animal.newBuilder() to construct.
    private Animal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Animal() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Animal();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Animal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProductOuterClass.internal_static_Animal_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProductOuterClass.internal_static_Animal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Animal.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Animal)) {
        return super.equals(obj);
      }
      Animal other = (Animal) obj;

      if (getId()
          != other.getId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Animal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Animal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Animal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Animal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Animal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Animal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Animal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Animal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Animal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Animal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Animal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Animal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Animal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Animal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Animal)
        AnimalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProductOuterClass.internal_static_Animal_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProductOuterClass.internal_static_Animal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Animal.class, Builder.class);
      }

      // Construct using sdj3.registerservice2.product.ProductOuterClass.Animal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProductOuterClass.internal_static_Animal_descriptor;
      }

      @Override
      public Animal getDefaultInstanceForType() {
        return Animal.getDefaultInstance();
      }

      @Override
      public Animal build() {
        Animal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Animal buildPartial() {
        Animal result = new Animal(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Animal) {
          return mergeFrom((Animal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Animal other) {
        if (other == Animal.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Animal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Animal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Animal)
    }

    // @@protoc_insertion_point(class_scope:Animal)
    private static final Animal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Animal();
    }

    public static Animal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Animal>
        PARSER = new com.google.protobuf.AbstractParser<Animal>() {
      @Override
      public Animal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Animal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Animal> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Animal> getParserForType() {
      return PARSER;
    }

    @Override
    public Animal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProductList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Product products = 1;</code>
     */
    java.util.List<Product>
        getProductsList();
    /**
     * <code>repeated .Product products = 1;</code>
     */
    Product getProducts(int index);
    /**
     * <code>repeated .Product products = 1;</code>
     */
    int getProductsCount();
    /**
     * <code>repeated .Product products = 1;</code>
     */
    java.util.List<? extends ProductOrBuilder>
        getProductsOrBuilderList();
    /**
     * <code>repeated .Product products = 1;</code>
     */
    ProductOrBuilder getProductsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ProductList}
   */
  public  static final class ProductList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProductList)
      ProductListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProductList.newBuilder() to construct.
    private ProductList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProductList() {
      products_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProductList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProductList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                products_ = new java.util.ArrayList<Product>();
                mutable_bitField0_ |= 0x00000001;
              }
              products_.add(
                  input.readMessage(Product.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          products_ = java.util.Collections.unmodifiableList(products_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProductOuterClass.internal_static_ProductList_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProductOuterClass.internal_static_ProductList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProductList.class, Builder.class);
    }

    public static final int PRODUCTS_FIELD_NUMBER = 1;
    private java.util.List<Product> products_;
    /**
     * <code>repeated .Product products = 1;</code>
     */
    public java.util.List<Product> getProductsList() {
      return products_;
    }
    /**
     * <code>repeated .Product products = 1;</code>
     */
    public java.util.List<? extends ProductOrBuilder>
        getProductsOrBuilderList() {
      return products_;
    }
    /**
     * <code>repeated .Product products = 1;</code>
     */
    public int getProductsCount() {
      return products_.size();
    }
    /**
     * <code>repeated .Product products = 1;</code>
     */
    public Product getProducts(int index) {
      return products_.get(index);
    }
    /**
     * <code>repeated .Product products = 1;</code>
     */
    public ProductOrBuilder getProductsOrBuilder(
        int index) {
      return products_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < products_.size(); i++) {
        output.writeMessage(1, products_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < products_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, products_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProductList)) {
        return super.equals(obj);
      }
      ProductList other = (ProductList) obj;

      if (!getProductsList()
          .equals(other.getProductsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getProductsCount() > 0) {
        hash = (37 * hash) + PRODUCTS_FIELD_NUMBER;
        hash = (53 * hash) + getProductsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProductList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProductList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProductList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProductList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProductList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProductList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProductList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProductList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProductList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProductList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProductList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProductList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProductList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProductList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProductList)
        ProductListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProductOuterClass.internal_static_ProductList_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProductOuterClass.internal_static_ProductList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProductList.class, Builder.class);
      }

      // Construct using sdj3.registerservice2.product.ProductOuterClass.ProductList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProductsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (productsBuilder_ == null) {
          products_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          productsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProductOuterClass.internal_static_ProductList_descriptor;
      }

      @Override
      public ProductList getDefaultInstanceForType() {
        return ProductList.getDefaultInstance();
      }

      @Override
      public ProductList build() {
        ProductList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ProductList buildPartial() {
        ProductList result = new ProductList(this);
        int from_bitField0_ = bitField0_;
        if (productsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            products_ = java.util.Collections.unmodifiableList(products_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.products_ = products_;
        } else {
          result.products_ = productsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProductList) {
          return mergeFrom((ProductList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProductList other) {
        if (other == ProductList.getDefaultInstance()) return this;
        if (productsBuilder_ == null) {
          if (!other.products_.isEmpty()) {
            if (products_.isEmpty()) {
              products_ = other.products_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureProductsIsMutable();
              products_.addAll(other.products_);
            }
            onChanged();
          }
        } else {
          if (!other.products_.isEmpty()) {
            if (productsBuilder_.isEmpty()) {
              productsBuilder_.dispose();
              productsBuilder_ = null;
              products_ = other.products_;
              bitField0_ = (bitField0_ & ~0x00000001);
              productsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProductsFieldBuilder() : null;
            } else {
              productsBuilder_.addAllMessages(other.products_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProductList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProductList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Product> products_ =
        java.util.Collections.emptyList();
      private void ensureProductsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          products_ = new java.util.ArrayList<Product>(products_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Product, Product.Builder, ProductOrBuilder> productsBuilder_;

      /**
       * <code>repeated .Product products = 1;</code>
       */
      public java.util.List<Product> getProductsList() {
        if (productsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(products_);
        } else {
          return productsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Product products = 1;</code>
       */
      public int getProductsCount() {
        if (productsBuilder_ == null) {
          return products_.size();
        } else {
          return productsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Product products = 1;</code>
       */
      public Product getProducts(int index) {
        if (productsBuilder_ == null) {
          return products_.get(index);
        } else {
          return productsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Product products = 1;</code>
       */
      public Builder setProducts(
          int index, Product value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.set(index, value);
          onChanged();
        } else {
          productsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 1;</code>
       */
      public Builder setProducts(
          int index, Product.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.set(index, builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 1;</code>
       */
      public Builder addProducts(Product value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.add(value);
          onChanged();
        } else {
          productsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 1;</code>
       */
      public Builder addProducts(
          int index, Product value) {
        if (productsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductsIsMutable();
          products_.add(index, value);
          onChanged();
        } else {
          productsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 1;</code>
       */
      public Builder addProducts(
          Product.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.add(builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 1;</code>
       */
      public Builder addProducts(
          int index, Product.Builder builderForValue) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.add(index, builderForValue.build());
          onChanged();
        } else {
          productsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 1;</code>
       */
      public Builder addAllProducts(
          Iterable<? extends Product> values) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, products_);
          onChanged();
        } else {
          productsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 1;</code>
       */
      public Builder clearProducts() {
        if (productsBuilder_ == null) {
          products_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          productsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 1;</code>
       */
      public Builder removeProducts(int index) {
        if (productsBuilder_ == null) {
          ensureProductsIsMutable();
          products_.remove(index);
          onChanged();
        } else {
          productsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Product products = 1;</code>
       */
      public Product.Builder getProductsBuilder(
          int index) {
        return getProductsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Product products = 1;</code>
       */
      public ProductOrBuilder getProductsOrBuilder(
          int index) {
        if (productsBuilder_ == null) {
          return products_.get(index);  } else {
          return productsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Product products = 1;</code>
       */
      public java.util.List<? extends ProductOrBuilder>
           getProductsOrBuilderList() {
        if (productsBuilder_ != null) {
          return productsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(products_);
        }
      }
      /**
       * <code>repeated .Product products = 1;</code>
       */
      public Product.Builder addProductsBuilder() {
        return getProductsFieldBuilder().addBuilder(
            Product.getDefaultInstance());
      }
      /**
       * <code>repeated .Product products = 1;</code>
       */
      public Product.Builder addProductsBuilder(
          int index) {
        return getProductsFieldBuilder().addBuilder(
            index, Product.getDefaultInstance());
      }
      /**
       * <code>repeated .Product products = 1;</code>
       */
      public java.util.List<Product.Builder>
           getProductsBuilderList() {
        return getProductsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Product, Product.Builder, ProductOrBuilder>
          getProductsFieldBuilder() {
        if (productsBuilder_ == null) {
          productsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Product, Product.Builder, ProductOrBuilder>(
                  products_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          products_ = null;
        }
        return productsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProductList)
    }

    // @@protoc_insertion_point(class_scope:ProductList)
    private static final ProductList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProductList();
    }

    public static ProductList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProductList>
        PARSER = new com.google.protobuf.AbstractParser<ProductList>() {
      @Override
      public ProductList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProductList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProductList> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ProductList> getParserForType() {
      return PARSER;
    }

    @Override
    public ProductList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AnimalListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AnimalList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    java.util.List<Animal>
        getAnimalsList();
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    Animal getAnimals(int index);
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    int getAnimalsCount();
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    java.util.List<? extends AnimalOrBuilder>
        getAnimalsOrBuilderList();
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    AnimalOrBuilder getAnimalsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code AnimalList}
   */
  public  static final class AnimalList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AnimalList)
      AnimalListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AnimalList.newBuilder() to construct.
    private AnimalList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AnimalList() {
      animals_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new AnimalList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AnimalList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                animals_ = new java.util.ArrayList<Animal>();
                mutable_bitField0_ |= 0x00000001;
              }
              animals_.add(
                  input.readMessage(Animal.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          animals_ = java.util.Collections.unmodifiableList(animals_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProductOuterClass.internal_static_AnimalList_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProductOuterClass.internal_static_AnimalList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AnimalList.class, Builder.class);
    }

    public static final int ANIMALS_FIELD_NUMBER = 1;
    private java.util.List<Animal> animals_;
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    public java.util.List<Animal> getAnimalsList() {
      return animals_;
    }
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    public java.util.List<? extends AnimalOrBuilder>
        getAnimalsOrBuilderList() {
      return animals_;
    }
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    public int getAnimalsCount() {
      return animals_.size();
    }
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    public Animal getAnimals(int index) {
      return animals_.get(index);
    }
    /**
     * <code>repeated .Animal animals = 1;</code>
     */
    public AnimalOrBuilder getAnimalsOrBuilder(
        int index) {
      return animals_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < animals_.size(); i++) {
        output.writeMessage(1, animals_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < animals_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, animals_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AnimalList)) {
        return super.equals(obj);
      }
      AnimalList other = (AnimalList) obj;

      if (!getAnimalsList()
          .equals(other.getAnimalsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAnimalsCount() > 0) {
        hash = (37 * hash) + ANIMALS_FIELD_NUMBER;
        hash = (53 * hash) + getAnimalsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AnimalList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnimalList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnimalList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnimalList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnimalList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnimalList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnimalList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AnimalList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AnimalList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AnimalList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AnimalList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AnimalList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AnimalList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AnimalList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AnimalList)
        AnimalListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProductOuterClass.internal_static_AnimalList_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProductOuterClass.internal_static_AnimalList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AnimalList.class, Builder.class);
      }

      // Construct using sdj3.registerservice2.product.ProductOuterClass.AnimalList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAnimalsFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (animalsBuilder_ == null) {
          animals_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          animalsBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProductOuterClass.internal_static_AnimalList_descriptor;
      }

      @Override
      public AnimalList getDefaultInstanceForType() {
        return AnimalList.getDefaultInstance();
      }

      @Override
      public AnimalList build() {
        AnimalList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public AnimalList buildPartial() {
        AnimalList result = new AnimalList(this);
        int from_bitField0_ = bitField0_;
        if (animalsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            animals_ = java.util.Collections.unmodifiableList(animals_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.animals_ = animals_;
        } else {
          result.animals_ = animalsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AnimalList) {
          return mergeFrom((AnimalList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AnimalList other) {
        if (other == AnimalList.getDefaultInstance()) return this;
        if (animalsBuilder_ == null) {
          if (!other.animals_.isEmpty()) {
            if (animals_.isEmpty()) {
              animals_ = other.animals_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAnimalsIsMutable();
              animals_.addAll(other.animals_);
            }
            onChanged();
          }
        } else {
          if (!other.animals_.isEmpty()) {
            if (animalsBuilder_.isEmpty()) {
              animalsBuilder_.dispose();
              animalsBuilder_ = null;
              animals_ = other.animals_;
              bitField0_ = (bitField0_ & ~0x00000001);
              animalsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAnimalsFieldBuilder() : null;
            } else {
              animalsBuilder_.addAllMessages(other.animals_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AnimalList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AnimalList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Animal> animals_ =
        java.util.Collections.emptyList();
      private void ensureAnimalsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          animals_ = new java.util.ArrayList<Animal>(animals_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Animal, Animal.Builder, AnimalOrBuilder> animalsBuilder_;

      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public java.util.List<Animal> getAnimalsList() {
        if (animalsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(animals_);
        } else {
          return animalsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public int getAnimalsCount() {
        if (animalsBuilder_ == null) {
          return animals_.size();
        } else {
          return animalsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Animal getAnimals(int index) {
        if (animalsBuilder_ == null) {
          return animals_.get(index);
        } else {
          return animalsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder setAnimals(
          int index, Animal value) {
        if (animalsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnimalsIsMutable();
          animals_.set(index, value);
          onChanged();
        } else {
          animalsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder setAnimals(
          int index, Animal.Builder builderForValue) {
        if (animalsBuilder_ == null) {
          ensureAnimalsIsMutable();
          animals_.set(index, builderForValue.build());
          onChanged();
        } else {
          animalsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder addAnimals(Animal value) {
        if (animalsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnimalsIsMutable();
          animals_.add(value);
          onChanged();
        } else {
          animalsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder addAnimals(
          int index, Animal value) {
        if (animalsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnimalsIsMutable();
          animals_.add(index, value);
          onChanged();
        } else {
          animalsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder addAnimals(
          Animal.Builder builderForValue) {
        if (animalsBuilder_ == null) {
          ensureAnimalsIsMutable();
          animals_.add(builderForValue.build());
          onChanged();
        } else {
          animalsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder addAnimals(
          int index, Animal.Builder builderForValue) {
        if (animalsBuilder_ == null) {
          ensureAnimalsIsMutable();
          animals_.add(index, builderForValue.build());
          onChanged();
        } else {
          animalsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder addAllAnimals(
          Iterable<? extends Animal> values) {
        if (animalsBuilder_ == null) {
          ensureAnimalsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, animals_);
          onChanged();
        } else {
          animalsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder clearAnimals() {
        if (animalsBuilder_ == null) {
          animals_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          animalsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Builder removeAnimals(int index) {
        if (animalsBuilder_ == null) {
          ensureAnimalsIsMutable();
          animals_.remove(index);
          onChanged();
        } else {
          animalsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Animal.Builder getAnimalsBuilder(
          int index) {
        return getAnimalsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public AnimalOrBuilder getAnimalsOrBuilder(
          int index) {
        if (animalsBuilder_ == null) {
          return animals_.get(index);  } else {
          return animalsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public java.util.List<? extends AnimalOrBuilder>
           getAnimalsOrBuilderList() {
        if (animalsBuilder_ != null) {
          return animalsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(animals_);
        }
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Animal.Builder addAnimalsBuilder() {
        return getAnimalsFieldBuilder().addBuilder(
            Animal.getDefaultInstance());
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public Animal.Builder addAnimalsBuilder(
          int index) {
        return getAnimalsFieldBuilder().addBuilder(
            index, Animal.getDefaultInstance());
      }
      /**
       * <code>repeated .Animal animals = 1;</code>
       */
      public java.util.List<Animal.Builder>
           getAnimalsBuilderList() {
        return getAnimalsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Animal, Animal.Builder, AnimalOrBuilder>
          getAnimalsFieldBuilder() {
        if (animalsBuilder_ == null) {
          animalsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Animal, Animal.Builder, AnimalOrBuilder>(
                  animals_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          animals_ = null;
        }
        return animalsBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AnimalList)
    }

    // @@protoc_insertion_point(class_scope:AnimalList)
    private static final AnimalList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AnimalList();
    }

    public static AnimalList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AnimalList>
        PARSER = new com.google.protobuf.AbstractParser<AnimalList>() {
      @Override
      public AnimalList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AnimalList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AnimalList> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AnimalList> getParserForType() {
      return PARSER;
    }

    @Override
    public AnimalList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Product_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Animal_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Animal_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProductList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimalList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimalList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rproduct.proto\"\025\n\007Product\022\n\n\002id\030\001 \001(\003\"\024" +
      "\n\006Animal\022\n\n\002id\030\001 \001(\003\")\n\013ProductList\022\032\n\010p" +
      "roducts\030\001 \003(\0132\010.Product\"&\n\nAnimalList\022\030\n" +
      "\007animals\030\001 \003(\0132\007.Animal2m\n\016ProductServic" +
      "e\022-\n\024GetProductWithAnimal\022\007.Animal\032\014.Pro" +
      "ductList\022,\n\023GetAnimalsInProduct\022\010.Produc" +
      "t\032\013.AnimalListb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Product_descriptor,
        new String[] { "Id", });
    internal_static_Animal_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Animal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Animal_descriptor,
        new String[] { "Id", });
    internal_static_ProductList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProductList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProductList_descriptor,
        new String[] { "Products", });
    internal_static_AnimalList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AnimalList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimalList_descriptor,
        new String[] { "Animals", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
